### ISSUE TITLE
Is it still working ?

### ISSUE THREAD

**Issue by Luke-2000** [Messere/listal-bot#2]
At first I want to thank you for this .... thank you ... ^^

I installed npm, node and listal-bot on my windows 7 machine .... i try also a test file and it worked (not to see on this pic, sorry)
![following](https://user-images.githubusercontent.com/48768756/54708695-3d4fa580-4b44-11e9-939a-4e9f2bea7d8c.png)
It is finish, but their is no single picture on the HDD ... what's the problem ?

I try it with command.exe, but on the other hand i try also node directly ... node call me this ...
![syntaxnode](https://user-images.githubusercontent.com/48768756/54708499-cd411f80-4b43-11e9-867d-9e6edbbf05dd.png)
Am I to stupid for the whole world ?!

**Comment by Messere** [comment]
No, you're not. Apparently it stopped working just today. 

I'll look into it, thanks for reporting.

**Comment by Messere** [comment]
Listal enabled some kind of protection on their pages. It checks if you're using real browser (or at least one that is able to interpret and run javascript) and blocks you otherwise. 

Listal-bot does not fulfill those requirements and gets:

![2019-03-20 21_43_10-gateway](https://user-images.githubusercontent.com/386388/54718370-a215fa80-4b5a-11e9-96d2-b54fd31d5212.png)

instead of real page with images. 

That's unfortunately **not** something that can be easily fixed.

**Comment by Luke-2000** [comment]
I don't know, if it will help, but since few days it is no longer possible, to surf on listal without enabled JavaScript ...

**Comment by HuntZero** [comment]
Nuts :( Been using this tool quite often... It's the only method that has worked on this site for quite sometime (browsers plugins such as downthemall, imggrabber etc don't work with listal)

**Comment by Messere** [comment]
New version is up, please reinstall: `npm install -g listal-bot`.

Note that:
- it's bigger, as it now depends on chromium browser (~100MB) in some stages of acquiring image links (it still works from console, chromium is used in "headless" mode),
- it's a bit slower (chromium is quite a big program to launch),
- downloading images from "lists" pages no longer works.

But at least it seems to be working again, let me know if it does not work for you.

**Comment by HuntZero** [comment]
Thanks for the quick update! I did a re-install, but it seems the system can't find it? Node is installed correctly. Where it did work before, now it just says: 

/usr/bin/env: ‘node\r’: No such file or directory

**Comment by Messere** [comment]
Hm... Looks like some line ending issue that didn't show up on my side (I tested it on windows 10 and linux). Anyway I tried to rebuild and publish the package on linux machine this time - try to update again (version should be 1.0.2) and check if that helps.

**Comment by HuntZero** [comment]
Am I missing something?

npm ERR! not a package /usr/local/bin/listal-bot
npm ERR! addLocal Could not install /usr/local/bin/listal-bot

**Comment by Messere** [comment]
I'm glad to hear that :)

**Comment by Luke-2000** [comment]
It works perfectly ... thank you ... ^^

**Comment by Messere** [comment]
Perfect 👍 
I'm closing the issue then.
