### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by HuntZero** [Messere/listal-bot#4]
As of today, getting this error message:  

Fatal error: Navigation Timeout Exceeded: 30000ms exceeded

**Comment by Messere** [comment]
Seems to be working fine for me. Are you sure it's not just a temporary issue?

**Comment by HuntZero** [comment]
Yup seems to be working now. Might be worth keeping an eye on it though, as I could still access the site fine but was getting no response from the bot. Thanks for the reply!

**Comment by HuntZero** [comment]
Scratch that, it's doing it again. It seems to occur after accessing a gallery in a browser and then going to use the listal-bot, or at least that's my theory for the moment.

**Comment by Messere** [comment]
Turns out the workaround for #2 is not needed anymore, so I simply reverted most of the recent changes (including the one related reported navigation timeout). 

Listal-bot should be smaller and faster again, and able to download lists again. Please upgrade.

**Comment by HuntZero** [comment]
Yup, working smoothly again. Though I have a hunch listal will roll out another set of changes sooner or later. ;)

**Comment by HuntZero** [comment]
As predicted, it's stopped working again. ;) Looks like a repeat of #2

**Comment by Messere** [comment]
Yes. JavaScript based "ddos protection" is back again, so is the workaround. Please update.

Next time I'm going to add autodetection if workaround is required ;)

**Comment by HuntZero** [comment]
Yup! We're playing glorified whack-a-mole at this point. :)

**Comment by HuntZero** [comment]
It worked briefly, gone again. I removed and re-install again to double check, but jobs just close with 'finished'

**Comment by Messere** [comment]
Recently I've learned about [cloudscraper](https://www.npmjs.com/package/cloudscraper) library, and decided to use it as an alternative to running headless chrome browser in the background. It seems to be working fine and is much more lightweight. 

Version 1.2.1 published, please upgrade. Let's see if it's more stable.
