### ISSUE TITLE
listal-bot not downloading all files

### ISSUE THREAD

**Issue by Eggy248** [Messere/listal-bot#6]
Messere,

Thanks again for this awesome tool. I was using it for the first time in a long while yesterday and today and am finding that not all of the files are being downloaded. There does not seem to be any pattern for the number of images downloaded. I wanted to bring it to your attention in case you can spend some time looking into it. Thanks.

Cheers!

**Comment by Messere** [comment]
Hi, 

There may be a several reasons for this:

1. Some of the files may be actually gone from listal server, although still listed and counted on their page.
2. Temporary server errors on listal side happen from time to time. Listal-bot tries several times to get an image, but gives up eventually. Re-running the same command after some time may help to download missing files.
3. Counters shown on listal pages are often inaccurate. E.g. `www.listal.com/petra-cubonova` claims there are 512 images, while in fact only two pages (around 65 images) exist when you start browsing them. Discrepancies like that are quite common, although not always as big and easy to verify. 

Can't rule out other glitches or mistakes on their or mine side, but without examples it's hard to verify.

**Comment by Messere** [comment]
Closing due to lack of feedback.
